### ISSUE TITLE
关于两台独立主机部署eureka高可用的问题！

### ISSUE THREAD

**Issue by hurukawatinami** [itmuch/spring-cloud-docker-microservice-book-code-docker#3]
@eacdy 周立老师，这边有个问题。按照《Spring Cloud与Docker微服务架构实战（第2版）》一书的<_14.7.2 编排高可用的Eureka Server章节_>，单机部署成功启动，两个eureka服务可以互相发现注册。

但是，我现在有个场景，就是在两台独立主机上，在docker中分别部署启动eureka_peer1和eureka_peer2，可以启动起来，但是不能互相发现注册。

望老师解答。

**Comment by eacdy** [comment]
@hurukawatinami 您好，将peer1注册到peer2，peer2注册到peer1即可。
您在两台机器无法成功注册，考虑是网络问题，例如A机器不知道B的主机名。可以去掉主机名(hostname)配置，直接用IP。

**Comment by hurukawatinami** [comment]
@eacdy 我试过用ip地址，不行。

两个独立的eureka地址分别是：
> http://192.168.159.211:7021
> http://192.168.159.212:7022

下面是eureka的yml配置文件：
```yml
server:
  port: 7021
spring:
  profiles: test-211
eureka:
  instance:
    hostname: discovery-211        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.159.212:7022/eureka/  #Eureka节点相互注册
      register-with-eureka: true

---

server:
  port: 7022
spring:
  profiles: test-212
eureka:
  instance:
    hostname: discovery-212        #Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.159.211:7021/eureka/  #Eureka节点相互注册
      register-with-eureka: true
```

**Comment by eacdy** [comment]
我的意思是 你在192.168.159.211 机器上`ping discovery-212` 看能不能通；在`192.168.159.212` 上ping下`ping discovery-211`能不能通；如果不能通，要么配置主机名，让它能ping通，要么就直接改成：
```yaml
# 公共部分
---
server:
  port: 7021
spring:
  profiles: test-211
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.159.212:7022/eureka/  #Eureka节点相互注册
      register-with-eureka: true

---

server:
  port: 7022
spring:
  profiles: test-212
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.159.211:7021/eureka/  #Eureka节点相互注册
      register-with-eureka: true
```
或者简写：
```yaml
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://192.168.159.212:7022/eureka/,http://192.168.159.211:7021/eureka/
---
server:
  port: 7021
spring:
  profiles: test-211
---
server:
  port: 7022
spring:
  profiles: test-212
```
